//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] IceBreak {
            get {
                object obj = ResourceManager.GetObject("IceBreak", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211112222222221112
        ///211111111111111112
        ///211111111111111112
        ///212112111211211212
        ///211111111111111112
        ///211111111111111112
        ///212311111111111212
        ///211111111111111112
        ///211111212111111112
        ///212111111111111212
        ///212111111111111212
        ///212111121121111212
        ///212111121121111212
        ///212111121121114212
        ///212111121121111212
        ///211122221122221112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_1 {
            get {
                return ResourceManager.GetString("stage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211111111111111112
        ///212222222222222212
        ///212411111111111112
        ///212231222222222222
        ///211121111111111122
        ///211112111111112122
        ///211111221111112112
        ///211111121111121112
        ///211111121111121112
        ///211111221111112112
        ///211112111111112122
        ///211121111111111122
        ///212211222222222222
        ///212211111111111112
        ///212222222222222212
        ///211111111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_2 {
            get {
                return ResourceManager.GetString("stage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211211111111111112
        ///211211111111111112
        ///211222221121222112
        ///211222221121211112
        ///211211221121211112
        ///211231111121222112
        ///211112111121111112
        ///241112222222222212
        ///211112222222222212
        ///211112111121111112
        ///211211111121222112
        ///211211221121211112
        ///211222221121211112
        ///211222221121222112
        ///211211111111111112
        ///211211111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_3 {
            get {
                return ResourceManager.GetString("stage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///241111111111111112
        ///211111111111111112
        ///222221122221122222
        ///211111111111111112
        ///211111111111111112
        ///222221122221122222
        ///211111111111111112
        ///212112112112112112
        ///212112112112112112
        ///212112112112112112
        ///212112112112112112
        ///212111111111111112
        ///211111111111111112
        ///222221122221122222
        ///211111211112111132
        ///211111111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_4 {
            get {
                return ResourceManager.GetString("stage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211111111111111112
        ///211111111111111112
        ///211111112211111112
        ///211111112211111112
        ///211111112211111112
        ///211111112211111112
        ///221211222222222122
        ///221211142222112122
        ///221211222231112122
        ///211111112222112122
        ///212111112211111112
        ///212112112211111112
        ///212222112211111112
        ///212112212211111112
        ///212111112211111112
        ///211111112211111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_5 {
            get {
                return ResourceManager.GetString("stage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211111111111111112
        ///212222222222222212
        ///212411111111111212
        ///212111111111111212
        ///212222221122222212
        ///211111121121111112
        ///211111121121111112
        ///211111111111111112
        ///211111111111111112
        ///211111121121111112
        ///211111121121111112
        ///212222221122222212
        ///212111111111111212
        ///212111111111113212
        ///212222222222222212
        ///211111111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_6 {
            get {
                return ResourceManager.GetString("stage_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///241112211112211112
        ///211112211112211112
        ///211112211112211112
        ///211112211112211112
        ///211111111111111112
        ///222222112211111222
        ///211111111111111112
        ///211111211112111112
        ///211111211112111112
        ///211111111111111112
        ///222111112211222222
        ///211111111111111112
        ///211112211112211112
        ///211112211112211112
        ///211112211112211112
        ///211112211112211132
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_7 {
            get {
                return ResourceManager.GetString("stage_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211111111111221112
        ///211111111111221112
        ///211111111111221112
        ///222222221121221112
        ///222222221121221112
        ///211111111121221112
        ///211122221121221112
        ///211111111111111112
        ///211111131111111112
        ///211122121122221112
        ///211122121111111112
        ///211122121122222222
        ///211122121122222222
        ///211122111111111112
        ///211122111111111112
        ///241122111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_8 {
            get {
                return ResourceManager.GetString("stage_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 222222222222222222
        ///211111111111111142
        ///211111111111111112
        ///211222222222222112
        ///211111111111112112
        ///211211111111112112
        ///211211222222112112
        ///211211232112112112
        ///211211211112112112
        ///211211211112112112
        ///211211211112112112
        ///211211222211112112
        ///211211111111112112
        ///211211111111112112
        ///211222222222222112
        ///211111111111111112
        ///211111111111111112
        ///222222222222222222 的當地語系化字串。
        /// </summary>
        internal static string stage_9 {
            get {
                return ResourceManager.GetString("stage_9", resourceCulture);
            }
        }
    }
}
